---
version: '3.4'
services:
  # Data Stores
  ## Kafka
  zk1:
    image: confluentinc/cp-zookeeper:${CP_VERSION}
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      ZOOKEEPER_REQUIRE_CLIENT_AUTH_SCHEME: sasl
      EXTRA_ARGS: "
        -Djava.security.auth.login.config=/etc/kafka/zookeeper_jaas.conf
        -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=1234:/opt/prometheus-jmx-exporter/zookeeper.yml
      "
    volumes:
      - ./prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
      - ./zk/zookeeper_jaas.conf:/etc/kafka/zookeeper_jaas.conf
  kafka1:
    image: confluentinc/cp-kafka:${CP_VERSION}
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 12
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_PLAINTEXT_HOST:SASL_PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092,PLAINTEXT_HOST://localhost:9092,SASL_PLAINTEXT://kafka1:19093,SASL_PLAINTEXT_HOST://localhost:9093

      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_OPTS: "
        -Djava.security.auth.login.config=/etc/kafka/kafka_jaas.conf
        -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=1234:/opt/prometheus-jmx-exporter/kafka-broker.yaml
      "
    volumes:
      - ./prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
      - ./sasl-plain/kafka_jaas.conf:/etc/kafka/kafka_jaas.conf
  schema-registry:
    image: confluentinc/cp-schema-registry:${CP_VERSION}
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka1:19092
  ## RabbitMQ
  rabbitmq1:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  # Connectors
  ## Kafka Connect cluster
  connect1:
    image: confluentinc/cp-kafka-connect:${CP_VERSION}
    ports:
      - 8083:8083
      - 5083:5083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka1:19092
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.converters.ByteArrayConverter
      CONNECT_PLUGIN_PATH: /usr/share/java,/connector
      KAFKA_OPTS: "-javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=5083:/opt/prometheus-jmx-exporter/kafka-connect.yaml"
    volumes:
      - ./prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
      - ./connector:/connector