team: "demo"
projects:
  - name: "test"
    topics:
      - name: "topic"
        config:
          replication.factor: "1"
          num.partitions: "1"
      - name: "topic-avro"
        config:
          replication.factor: "1"
          num.partitions: "1"
      - name: "topic-json"
        config:
          replication.factor: "1"
          num.partitions: "1"
      - name: "topic-json-schema"
        config:
          replication.factor: "1"
          num.partitions: "1"
